/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.invoice.ejb;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * <p>
 * LocalHome interface for the <code>InvoiceManager</code>. It contains only a single no-param
 * <code>create</code> method that produces an instance of the local interface. it is used to obtain a handle to
 * the stateless <code>SessionBean</code>.
 * </p>
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety is dependent on the
 * container.
 * </p>
 *
 * @author fabrizyo, enefem21
 * @version 1.0
 */
public interface InvoiceManagerLocalHome extends EJBLocalHome {

    /**
     * <p>
     * Creates an instance of <code>InvoiceManagerLocal</code>, which is a handle to the
     * <code>SessionBean</code>.
     * </p>
     *
     * @return an instance of <code>InvoiceManagerLocal</code>
     *
     * @throws CreateException
     *             This exception is used as a standard application-level exception to report a failure to create
     *             an entity EJB object
     */
    public InvoiceManagerLocal create() throws CreateException;
}
