/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.invoice.ejb;

import com.topcoder.timetracker.invoice.InvoiceManager;
import javax.ejb.EJBLocalObject;

/**
 * <p>
 * Local interface for <code>InvoiceManager</code>. It contains exactly the same methods as
 * <code>InvoiceManager</code> interface.
 * </p>
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety is dependent on the
 * container.
 * </p>
 *
 * @author fabrizyo, enefem21
 * @version 1.0
 */
public interface InvoiceManagerLocal extends InvoiceManager, EJBLocalObject {
}
