/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.entry.fixedbilling.j2ee;

import com.topcoder.timetracker.entry.fixedbilling.FixedBillingEntryManager;

import javax.ejb.EJBLocalObject;


/**
 * <p>
 * Local interface for <code>FixedBillingEntryManager</code>. It contains exactly the same methods as
 * <code>FixedBillingEntryManager</code> interface.
 * </p>
 *
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety is dependent on the container.
 * </p>
 *
 * @author ShindouHikaru, flytoj2ee
 * @version 1.0
 */
public interface FixedBillingEntryManagerLocal extends FixedBillingEntryManager, EJBLocalObject {
}
