/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.entry.fixedbilling.j2ee;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;


/**
 * <p>
 * LocalHome interface for the <code>FixedBillingStatusManager</code>. It contains only a single no-param create
 * method that produces an instance of the local interface. It is used to obtain a handle to the Stateless SessionBean.
 * </p>
 *
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety is dependent on the container.
 * </p>
 *
 * @author ShindouHikaru, flytoj2ee
 * @version 1.0
 */
public interface FixedBillingStatusManagerLocalHome extends EJBLocalHome {
    /**
     * <p>
     * Creates an instance of FixedBillingStatusManagerLocal, which is a handle to the SessionBean.
     * </p>
     *
     * @return an instance of FixedBillingStatusManagerLocal
     */
    FixedBillingStatusManagerLocal create() throws CreateException;
}
