package com.topcoder.controlpanel.clientassociations.dao.hibernate;
// Generated 2007-12-8 12:51:43 by Hibernate Tools 3.2.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer clientId;
     private String name;
     private Set<CompClient> compClients = new HashSet<CompClient>(0);
     private Set<UserClient> userClients = new HashSet<UserClient>(0);

    public Client() {
    }

	
    public Client(Integer clientId, String name) {
        this.clientId = clientId;
        this.name = name;
    }
    public Client(Integer clientId, String name, Set<CompClient> compClients, Set<UserClient> userClients) {
       this.clientId = clientId;
       this.name = name;
       this.compClients = compClients;
       this.userClients = userClients;
    }
   
    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<CompClient> getCompClients() {
        return this.compClients;
    }
    
    public void setCompClients(Set<CompClient> compClients) {
        this.compClients = compClients;
    }
    public Set<UserClient> getUserClients() {
        return this.userClients;
    }
    
    public void setUserClients(Set<UserClient> userClients) {
        this.userClients = userClients;
    }




}


