INSERT INTO tc_direct_project (project_id,name,description,user_id,create_date,modify_date) VALUES(1,'test','test',1,TO_DATE('2009-08-13 09:00:00', '%Y-%m-%d %H:%M:%S'),TO_DATE('2009-08-13 09:00:00', '%Y-%m-%d %H:%M:%S'));
INSERT INTO submission_type_lu (submission_type_id, submission_type_desc) VALUES (1, 'Final Fix');
INSERT INTO submission_type_lu (submission_type_id,submission_type_desc) VALUES (2, 'milestone submission type');
INSERT INTO submission_type_lu (submission_type_id,submission_type_desc) VALUES (3, 'final submission type');
INSERT INTO submission_status_lu (submission_status_id, submission_status_desc) VALUES (1, 'reviewed');
INSERT INTO submission_status_lu (submission_status_id, submission_status_desc) VALUES (2, 'deleted');
INSERT INTO path (path_id, path, modify_date) VALUES (1, '/root/', TO_DATE('2008-03-16 12:53:45', '%Y-%m-%d %H:%M:%S'));
INSERT INTO contest_status_lu (contest_status_id, contest_status_desc) VALUES (1, 'competition');
INSERT INTO file_type_lu (file_type_id, file_type_desc, sort, image_file_ind, extension) VALUES (1, 'Requirement Specification', 1, 1, '.pdf');
INSERT INTO prize_type_lu (prize_type_id, prize_type_desc) VALUES (1, 'Winner');
INSERT INTO payment_status_lu (payment_status_id, payments_status_desc) VALUES (1, 'hold');
INSERT INTO payment_status_lu (payment_status_id, payments_status_desc) VALUES (2, 'deleted');
INSERT INTO review_status_lu (review_status_id, review_status_desc) VALUES (1, 'hold');
INSERT INTO review_status_lu (review_status_id, review_status_desc) VALUES (2, 'deleted');
INSERT INTO contest_channel_lu (contest_channel_id, contest_channel_desc) VALUES (1, 'test_channel');
INSERT INTO contest_type_lu (contest_type_id, contest_type_desc,require_preview_image, require_preview_file) VALUES (1, 'DESIGN','F','T');
INSERT INTO contest_detailed_status_lu(contest_detailed_status_id,contest_detailed_status_desc,name,contest_status_id) VALUES (1,'detail competition','detail',1);
INSERT INTO contest_milestone_prize(contest_milestone_prize_id,prize_type_id,amount, number_of_submissions,create_date) VALUES(1,1,500,2,TO_DATE('2009-08-13 09:00:00', '%Y-%m-%d %H:%M:%S'));
INSERT INTO contest_general_info(contest_general_info_id) VALUES(1);
INSERT INTO contest_multi_round_information(contest_multi_round_information_id) VALUES(1);
INSERT INTO contest_specifications(contest_specifications_id) VALUES (1);
INSERT INTO contest (contest_id, contest_channel_id, name, contest_type_id, project_id, tc_direct_project_id, contest_status_id, contest_detailed_status_id, forum_id, event_id, start_time, end_time,  winner_announcement_time, create_user_id, contest_milestone_prize_id, contest_general_info_id, contest_multi_round_information_id, contest_specifications_id) VALUES(1, 1, 'Submission Mananger', 1, 1, 1, 1, 1,1, 1, TO_DATE('2008-03-13 09:00:00', '%Y-%m-%d %H:%M:%S'), TO_DATE('2008-03-20 09:00:00', '%Y-%m-%d %H:%M:%S'), TO_DATE('2008-03-22 09:00:00', '%Y-%m-%d %H:%M:%S'), 1,1,1,1,1);
INSERT INTO mime_type_lu (mime_type_id,file_type_id,mime_type_desc) VALUES(1,1,'test mime');