/*
 * Copyright (C) 2008 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.service.digitalrun.points.dao.implementations;

import java.util.List;

import javax.persistence.EntityExistsException;
import javax.persistence.EntityManager;
import javax.persistence.Query;

import com.topcoder.service.digitalrun.entity.DigitalRunPointsStatus;
import com.topcoder.service.digitalrun.points.DigitalRunPointsManagerPersistenceException;
import com.topcoder.service.digitalrun.points.DigitalRunPointsStatusDAO;
import com.topcoder.service.digitalrun.points.EntityNotFoundException;
import com.topcoder.service.digitalrun.points.Helper;

/**
 * <p>
 * This class implements DigitalRunPointsStatusDAO interface. It also extends the AbstractDAO class.
 * This class manages DigitalRunPointsStatus entities in a JPA persistence (currently the JPA
 * persistence will use Hibernate as a provider but any provider can be used). Each public method
 * performs logging.
 * </p>
 * <p>
 * Thread Safety: This class is not completely thread safe because it doesn't manage transactions
 * and it is also mutable. Anyway, the intent is to use this implementation in a stateless session
 * bean so there will be no thread safety issues generated by this class since the container will
 * ensure thread safety.
 * </p>
 * @author DanLazar, TCSDEVELOPER
 * @version 1.0
 */
public class JPADigitalRunPointsStatusDAO extends AbstractDAO implements DigitalRunPointsStatusDAO {
    /**
     * Present the class name.
     */
    private static final String CLASS_NAME = JPADigitalRunPointsStatusDAO.class.getName();

    /**
     * Default constructor.
     */
    public JPADigitalRunPointsStatusDAO() {
        // Empty
    }

    /**
     * Creates a new digital run points status entity into persistence. Returns the
     * DigitalRunPointsStatus instance with id generated.
     * @throws IllegalArgumentException
     *             if argument is null or if its id >0
     * @throws DigitalRunPointsManagerPersistenceException
     *             if any errors occur when accessing the persistent storage
     * @param pointsStatus
     *            the entity to be created
     * @return entity with id set
     */
    public DigitalRunPointsStatus createDigitalRunPointsStatus(DigitalRunPointsStatus pointsStatus)
            throws DigitalRunPointsManagerPersistenceException {
        String methodName = CLASS_NAME + ".createDigitalRunPointsStatus()";
        // Log the entrance
        Helper.logEntranceInfo(getLogger(), methodName);

        Helper.checkNullWithLog(pointsStatus, "pointsStatus", getLogger(), methodName);
        Helper.checkPositiveWithLog(pointsStatus.getId(), "pointsStatus.id", getLogger(), methodName);

        // obtain the EntityManager instance
        EntityManager em = getEntityManager();
        // persist the digital run points status entity in the database
        try {
            em.getTransaction().begin();
            em.persist(pointsStatus);
            em.getTransaction().commit();
        } catch (EntityExistsException e) {
            em.getTransaction().rollback();
            Helper.throwPersitenceExceptionWithLog("EntityExistsException occurs while do persisting.", e,
                    getLogger(), methodName);
        }

        // Log the exit
        Helper.logExitInfo(getLogger(), methodName);
        return pointsStatus;
    }

    /**
     * Updates the given digital run points status entity into persistence.
     * @throws IllegalArgumentException
     *             if argument is null
     * @throws EntityNotFoundException
     *             if a digital run points status entity with digital run points status entity
     *             argument id does not exist in the persistence
     * @throws DigitalRunPointsManagerPersistenceException
     *             if any errors occur when accessing the persistent storage
     * @param pointsStatus
     *            the entity to be updated
     */
    public void updateDigitalRunPointsStatus(DigitalRunPointsStatus pointsStatus)
            throws EntityNotFoundException, DigitalRunPointsManagerPersistenceException {
        String methodName = CLASS_NAME + ".updateDigitalRunPointsStatus()";
        // Log the entrance
        Helper.logEntranceInfo(getLogger(), methodName);

        Helper.checkNullWithLog(pointsStatus, "pointsStatus", getLogger(), methodName);

        // obtain the EntityManager instance
        EntityManager em = this.getEntityManager();
        // update the entity
        try {
            em.getTransaction().begin();
            em.merge(pointsStatus);
            em.getTransaction().commit();
        } catch (IllegalArgumentException iae) {
            em.getTransaction().rollback();
            Helper.throwEntityNotFoundExceptionWithLog("The pointsStatus is not exist.", iae, getLogger(),
                    methodName);
        }

        // Log the exit
        Helper.logExitInfo(getLogger(), methodName);
    }

    /**
     * Removes the digital run points status entity identified by the given id from persistence.
     * @throws IllegalArgumentException
     *             if argument<0
     * @throws EntityNotFoundException
     *             if there is no digital run points status entity with the given id in persistence
     * @throws DigitalRunPointsManagerPersistenceException
     *             if any errors occur when accessing the persistent storage
     * @param pointsStatusId
     *            the id that identified the entity to be removed
     */
    public void removeDigitalRunPointsStatus(long pointsStatusId) throws EntityNotFoundException,
            DigitalRunPointsManagerPersistenceException {
        String methodName = CLASS_NAME + ".removeDigitalRunPointsStatus()";
        // Log the entrance
        Helper.logEntranceInfo(getLogger(), methodName + " With Id[" + pointsStatusId + "]");

        Helper.checkNegativeWithLog(pointsStatusId, "pointsStatusId", getLogger(), methodName);

        // obtain the EntityManager instance
        EntityManager em = this.getEntityManager();
        // get the DigitalRunPointsStatus instance to be removed
        DigitalRunPointsStatus pointsStatus = em.find(DigitalRunPointsStatus.class, new Long(pointsStatusId));
        if (pointsStatus == null) {
            Helper.throwEntityNotFoundExceptionWithLog("DigitalRunPointsStatus with id[" + pointsStatusId
                    + "] is not exist.", null, getLogger(), methodName);
        }
        em.getTransaction().begin();
        // remove the entity
        em.remove(pointsStatus);
        em.getTransaction().commit();

        // Log the exit
        Helper.logExitInfo(getLogger(), methodName);
    }

    /**
     * Gets the digital run points status entity identified by the given id from persistence.
     * @throws IllegalArgumentException
     *             if argument<0
     * @throws EntityNotFoundException
     *             if there is no digital run points status entity with the given id in persistence
     * @throws DigitalRunPointsManagerPersistenceException
     *             if any errors occur when accessing the persistent storage
     * @param pointsStatusId
     *            the id that identifies the entity top be retrieved
     * @return the entity identified by the id
     */
    public DigitalRunPointsStatus getDigitalRunPointsStatus(long pointsStatusId)
            throws EntityNotFoundException, DigitalRunPointsManagerPersistenceException {
        String methodName = CLASS_NAME + ".getDigitalRunPointsStatus()";
        // Log the entrance
        Helper.logEntranceInfo(getLogger(), methodName + " With Id[" + pointsStatusId + "]");

        Helper.checkNegativeWithLog(pointsStatusId, "pointsStatusId", getLogger(), methodName);

        // obtain the EntityManager instance
        EntityManager em = this.getEntityManager();
        // get and return the digital run points status entity from the database
        DigitalRunPointsStatus pointsStatus = em.find(DigitalRunPointsStatus.class, new Long(pointsStatusId));
        if (pointsStatus == null) {
            Helper.throwEntityNotFoundExceptionWithLog("DigitalRunPointsStatus with id[" + pointsStatusId
                    + "] is not exist.", null, getLogger(), methodName);
        }

        // Log the exit
        Helper.logExitInfo(getLogger(), methodName);
        return pointsStatus;
    }

    /**
     * Gets all the digital run points statuses from persistence. If there is no such entity in
     * persistence an empty list is returned.
     * @throws DigitalRunPointsManagerPersistenceException
     *             if any errors occur when accessing the persistent storage
     * @return a list containing all statuses or an empty list if there is no such entity
     */
    public List<DigitalRunPointsStatus> getAllDigitalRunPointsStatuses()
            throws DigitalRunPointsManagerPersistenceException {
        String methodName = CLASS_NAME + ".getAllDigitalRunPointsStatuses()";
        // Log the entrance
        Helper.logEntranceInfo(getLogger(), methodName);

        // get the EntityManager instance
        EntityManager em = this.getEntityManager();
        // create a query that will retrieve all the rows from dr_points_status_lu table
        // create a Query instance
        Query query = em.createQuery("from DigitalRunPointsStatus");
        // retrieve the result
        List res = query.getResultList();

        // Log the exit
        Helper.logExitInfo(getLogger(), methodName);
        return res;
    }
}
