/// CSharpClass File "DefaultWebBrowserNavigator.cs" generated by Poseidon for UML.
/// Poseidon for UML is developed by <A HREF="http://www.gentleware.com">Gentleware</A>.
/// Generated with <A HREF="http://jakarta.apache.org/velocity/">velocity</A> template engine.

 namespace Orpheus_Client_Logic_for_MSIE {
   namespace Orpheus {
     namespace Plugin {
       namespace InternetExplorer {

         ///  <summary>
         ///  </summary>
         public class DefaultWebBrowserNavigator : Orpheus.Plugin.InternetExplorer.IWebBrowserWindowNavigator {

           /// Attributes

           /// Attribute newWindow
           private Orpheus.Plugin.InternetExplorer.Interop.IHTMLWindow2 newWindow = null;

           /// Attribute docHostUIHandler
           private Orpheus.Plugin.InternetExplorer.Interop.IDocHostUIHandler docHostUIHandler = <<constructor>>;

           /// Attribute context
           private  context = <<constructor>>;

           /// Attributes - AssociationEnd

           /// Association End iHTMLWindow2
           public Orpheus.Plugin.InternetExplorer.Interop.IHTMLWindow2 iHTMLWindow2;

           /// Operations

           /// Constructor DefaultWebBrowserNavigator
           /// <param name='context'></param>
           /// <param name='docHostUIHandler'></param>
           public DefaultWebBrowserNavigator( context, Orpheus.Plugin.InternetExplorer.Interop.IDocHostUIHandler docHostUIHandler) {
           }

           /// Operation Navigate
           /// <param name='browser'></param>
           /// <param name='url'></param>
           /// <param name='newWindow'></param>
           public void Navigate( browser, string url, bool newWindow) {
           
        // your code here
           
           }
         }

       }
     }
   }
 }
