
/// CSharpInterface File "IPersistence.cs" generated by Poseidon for UML.
/// Poseidon for UML is developed by <A HREF="http://www.gentleware.com">Gentleware</A>.
/// Generated with <A HREF="http://jakarta.apache.org/velocity/">velocity</A> template engine.

 namespace Orpheus_Client_Logic_for_MSIE {
   namespace Orpheus {
     namespace Plugin {
       namespace InternetExplorer {

         ///  <summary>
         ///  This interface defines the contract that is required for any persistence mechanism to implement. A persistence mechanism is responsible for saving and retrieving simple values for a specified key.
         ///  <p class="MsoNormal">This component provides an implementation of this interface that stores per user the values in the registry.</p>
         ///  <p class="MsoNormal"><strong>Thread safety: </strong>Implementations of this interface are expected to be thread safe.</p>
         ///  <!--EndFragment-->         ///  </summary>
         public interface IPersistence {



           /// Operations

           /// Operation this
           /// <summary>
           /// <p>This is the declaration of the indexer used to store or get a value based on a key.</p>           /// </summary>
           /// <exception>PersistenceException should be thrown by implementations if anything goes wrong whlie getting or storing a value.</exception>
           /// <param name='key'>The key to get or store the value for.</param>
           string this(string key) {
           }
         }

       }
     }
   }
 }
