update categories set parent_category_id = null;
delete from comp_dependencies;
delete from comp_documentation;
delete from comp_jive_category_xref;
delete from comp_link;
delete from comp_user;
delete from comp_technology;
delete from comp_version_dates;
delete from category_catalog;
delete from catalog;
delete from comp_categories;
delete from categories;
delete from technology_types;
delete from client;
delete from user_client;
delete from comp_client;
delete from comp_versions;
delete from comp_catalog;
delete from phase;
delete from doc_types;
commit;