DELETE FROM contact_relation;
DELETE FROM address_relation;
DELETE FROM contact;
DELETE FROM address;
DELETE FROM address_type;
DELETE FROM contact_type;
DELETE FROM state_name;
DELETE FROM country_name;
DELETE FROM id_sequences;