/*
 * Copyright (C) 2011 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.payments.amazonfps.model;

import java.io.Serializable;

import com.topcoder.payments.amazonfps.Helper;

/**
 * <p>
 * This class is a container for information about a single payment operation stored in persistence. Its main purpose
 * is to store request IDs generated by <i>Amazon FPS Service</i> for future troubleshooting purposes.
 * </p>
 *
 * <p>
 * It is a simple JavaBean (POJO) that provides getters and setters for all private attributes and performs no
 * argument validation in the setters.
 * </p>
 *
 * <strong>Thread Safety:</strong> This class is mutable and not thread safe.
 *
 * @author saarixx, KennyAlive
 * @version 1.0
 */
public class PaymentOperation implements Serializable {
    /**
     * The class's serialVersionUID for the serialization runtime.
     */
    private static final long serialVersionUID = 1553693208434046430L;

    /**
     * The ID of the payment operation.
     * Can be any value. Has getter and setter.
     */
    private long id;

    /**
     * The ID of the payment.
     * Can be any value. Has getter and setter.
     */
    private long paymentId;

    /**
     * The ID of the request generated by <i>Amazon FPS Service</i>.
     * Can be any value. Has getter and setter.
     */
    private String requestId;

    /**
     * The type of the payment operation.
     * Can be any value. Has getter and setter.
     */
    private PaymentOperationType type;

    /**
     * The value indicating whether the payment operation was successful.
     * Can be any value. Has getter and setter.
     */
    private boolean successful;

    /**
     * Constructs new {@code PaymentOperation} instance.
     */
    public PaymentOperation() {
        // Empty
    }

    /**
     * Retrieves the ID of the payment operation.
     *
     * @return the ID of the payment operation
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the ID of the payment operation.
     *
     * @param id
     *          the ID of the payment operation
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Retrieves the ID of the payment.
     *
     * @return the ID of the payment
     */
    public long getPaymentId() {
        return paymentId;
    }

    /**
     * Sets the ID of the payment.
     *
     * @param paymentId
     *              the ID of the payment
     */
    public void setPaymentId(long paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * Retrieves the ID of the request generated by <i>Amazon FPS Service</i>.
     *
     * @return the ID of the request generated by <i>Amazon FPS Service</i>
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the ID of the request generated by <i>Amazon FPS Service</i>.
     *
     * @param requestId
     *              the ID of the request generated by <i>Amazon FPS Service</i>
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * Retrieves the type of the payment operation.
     *
     * @return the type of the payment operation
     */
    public PaymentOperationType getType() {
        return type;
    }

    /**
     * Sets the type of the payment operation.
     *
     * @param type
     *              the type of the payment operation
     */
    public void setType(PaymentOperationType type) {
        this.type = type;
    }

    /**
     * Retrieves the value indicating whether the payment operation was successful.
     *
     * @return the value indicating whether the payment operation was successful
     */
    public boolean isSuccessful() {
        return successful;
    }

    /**
     * Sets the value indicating whether the payment operation was successful.
     *
     * @param successful
     *              the value indicating whether the payment operation was successful
     */
    public void setSuccessful(boolean successful) {
        this.successful = successful;
    }

    /**
     * Converts this object to string presentation.
     *
     * @return string presentation of this object
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("{id: ").append(id)
          .append(", paymentId: ").append(paymentId)
          .append(", requestId: ").append(Helper.toString(requestId))
          .append(", type: ").append(Helper.toString(type))
          .append(", successful: ").append(successful)
          .append("}");
        return sb.toString();
    }
}
