/*
 * Copyright (C) 2009 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.service.studio.ejb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * This class represents the "illegal_argument_fault" element in WSDL. It's
 * contained in the related exception-illegalArgumentMessage class. It was
 * generated by JBoss tools and I changed the name and other little changes.
 * </p>
 *
 * <p>
 * This class is not thread safe because it's highly mutable
 * </p>
 *
 * @author fabrizyo, TCSDEVELOPER
 * @version 1.0
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "illegalArgumentMessage" })
@XmlRootElement(name = "illegal_argument_fault")
public class IllegalArgumentWSFault {
    /**
     * <p>
     * Represents the illegal argument message.
     * </p>
     */
    @XmlElement(name = "illegal_argument_fault", required = true)
    private String illegalArgumentMessage;

    /**
     * <p>
     * This is the default constructor. It does nothing.
     * </p>
     */
    public IllegalArgumentWSFault() {
    }

    /**
     * <p>
     * Gets the value of the illegalArgumentMessage property.
     * </p>
     *
     * @return the value of the illegalArgumentMessage property.
     */
    public String getIllegalArgumentMessage() {
        return illegalArgumentMessage;
    }

    /**
     * <p>
     * Sets the value of the illegalArgumentMessage property.
     * </p>
     *
     * @param illegalArgumentMessage the value of the illegalArgumentMessage
     *        property to set
     */
    public void setIllegalArgumentMessage(String illegalArgumentMessage) {
        this.illegalArgumentMessage = illegalArgumentMessage;
    }
}
