
package com.topcoder.timetracker.project.ejb;
import com.topcoder.naming.jndiutility.JNDIUtils;
import com.topcoder.util.config.ConfigManager;
/**
 * <p>
 * Local interface for ProjectUtility.  It contains exactly the same methods
 * as ProjectUtility interface.
 * </p>
 * <p>
 * Thread Safety:
 *  Implementation will be generated by EJB container and thread-safety
 * is dependent on the container.
 * </p>
 * 
 * @poseidon-object-id [Im4ce6b8c2m1110f96698cm386a]
 */
public interface ProjectUtilityLocal extends javax.ejb.EJBLocalObject, com.topcoder.timetracker.project.ProjectUtility {
}


