insert into third_party_library values("log4net","1.2.9","http://www.log4net.org","GPL","do logging","the path","the alias","the note",".NET");
insert into project values(13,'HBS Singleton Process Manager','1.0.0','Java','development',CURRENT);
insert into project values(14,'HBS Singleton Process Manager','1.0.0','Java','design',CURRENT);
insert into project_result  values('sparemax',13,1);
insert into project_result  values('EveningSun',13,2);
insert into project_result  values('Luca',14,1);
insert into project_result  values('AleaActaEst',14,2);
insert into submission_review values('bbxiong',13);
insert into submission_review values('Veloerien',13);
insert into submission_review values('FireIce',13);
insert into submission_review values('Rica',14);
insert into submission_review values('Telly12',14);
insert into submission_review values('linwe',14);
insert into project_info values(8,13,"http://localhost:8080/build-dependencies.xml");
insert into project_info values(8,14,"http://localhost:8080/build-dependencies.xml");