#include "nsISupports.idl"

[scriptable, uuid(68d70007-88ec-4a69-9d4c-67eac7f2d2af)]
interface tcIOrpheusScripting : nsISupports
{
    // these method are exposed for scripting
    void LoggedIn();
    
    void LoggedOut();
    
    void SetWorkingGame(in long aGameId);
    
    long GetWorkingGame();
    
    void SetCurrentTarget(in string aTargetHash, in string aURLHash, in long aSequence);
    
    void PollMessages();
    
    boolean IsPopup(in nsISupports aWindow);
};