/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.entry.time.ejb;

import javax.ejb.EJBLocalObject;

import com.topcoder.timetracker.entry.time.TaskTypeManager;

/**
 * <p>
 * This is the local interface for <code>TaskTypeManager</code>.
 * </p>
 *
 * <p>
 * It contains exactly the same methods as <code>TaskTypeManager</code> interface.
 * </p>
 *
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety
 * is dependent on the container.
 * </p>
 *
 * @author ShindouHikaru, TCSDEVELOPER
 * @version 3.2
 */
public interface TaskTypeManagerLocal extends TaskTypeManager, EJBLocalObject {
}
