/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.entry.time.ejb;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * <p>
 * This is the local home interface for the <code>TaskTypeManager</code>.
 * </p>
 *
 * <p>
 * It contains only a single no-param create method that produces an instance of the
 * local interface.  It is used to obtain a handle to the Stateless SessionBean.
 * </p>
 *
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety
 * is dependent on the container.
 * </p>
 *
 * @author ShindouHikaru, TCSDEVELOPER
 * @version 3.2
 */
public interface TaskTypeManagerLocalHome extends EJBLocalHome {
    /**
     * <p>
     * Creates an instance of <code>TaskTypeManagerLocal</code>, which is a
     * handle to the <code>SessionBean</code>.
     * </p>
     *
     * @return an instance of <code>TaskTypeManagerLocal</code>
     */
    public TaskTypeManagerLocal create() throws CreateException;
}
