delete from address_relation;
delete from contact_relation;
delete from address;
delete from contact;
delete from address_type;
delete from contact_type;
delete from country_name;
delete from state_name;
delete from company;
