
package com.topcoder.timetracker.audit.ejb;
import com.topcoder.timetracker.audit.ejb.AuditLocalObject;
/**
 * <p>
 * LocalHome interface for the AuditSessionBean.  It contains only a
 * single no-param create method that produces an instance of the 
 * local interface.  it is used to obtain a handle to the Stateless 
 * SessionBean.
 * </p>
 * <p>
 * Thread Safety:
 *  Implementation will be generated by EJB container and thread-safety
 * is dependent on the container.
 * </p>
 * 
 * @poseidon-object-id [I1a8685a4m1113fbd4f95mm5b5a]
 */
public interface AuditLocalHome extends javax.ejb.EJBLocalHome {
/**
 * <p>
 * Creates an instance of AudtiLocalObject, which is a 
 * handle to the AuditSessionBean.
 * </p>
 * 
 * @poseidon-object-id [I1a8685a4m1113fbd4f95mm5b22]
 * @return 
 * @throws CreateException if the attempt to create an AuditLocalObject fails
 */
    public com.topcoder.timetracker.audit.ejb.AuditLocalObject create();
}


