
package com.topcoder.timetracker.audit.ejb;

import com.topcoder.timetracker.audit.AuditManager;

/**
 * <p>
 * Local interface for AuditSessionBean.  It contains exactly the same methods
 * as AuditManager interface.
 * </p>
 * <p>
 * Thread Safety:
 *  Implementation will be generated by EJB container and thread-safety
 * is dependent on the container.
 * </p>
 * 
 * @poseidon-object-id [I1a8685a4m1113fbd4f95mm5b92]
 */
public interface AuditLocalObject extends javax.ejb.EJBLocalObject, AuditManager {
}


