[
        object,
        uuid(F1DB8392-7331-11D0-8C99-00A0C92DBFE8),
        pointer_default(unique),
        local
]
interface IInputObjectSite : IUnknown
{
    HRESULT OnFocusChangeIS([in] IUnknown * punkObj, BOOL fSetFocus);
}