
/// CSharpInterface File "IDocHostUIHandler.cs" generated by Poseidon for UML.
/// Poseidon for UML is developed by <A HREF="http://www.gentleware.com">Gentleware</A>.
/// Generated with <A HREF="http://jakarta.apache.org/velocity/">velocity</A> template engine.

 namespace Orpheus_Client_Logic_for_MSIE {
   namespace Orpheus {
     namespace Plugin {
       namespace InternetExplorer {
         namespace Interop {

           ///  <summary>
           ///  </summary>
           public interface IDocHostUIHandler {


           }

         }
       }
     }
   }
 }
