/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.entry.base.ejb;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;


/**
 * <p> LocalHome interface for the EntitySessionBean. It contains only a single no-param create method that
 * produces an instance of the local interface. it is used to obtain a handle to the Stateless SessionBean. </p>
 * <p> Thread Safety: Implementation will be generated by EJB container and thread-safety is dependent on the
 *  container. </p>
 *
 * @author bendlund, TCSDEVELOPER
 * @version 3.2
  */
public interface EntryLocalHome extends EJBLocalHome {
    /**
     * <p>Creates an instance of EntityLocalObject, which is a handle to the EntitySessionBean.</p>
     *
     * @return non-null EntryLocalObject
     *
     * @throws javax.ejb.CreateException if EntryLocalObject can't be created
     */
    public EntryLocalObject create() throws CreateException;
}
