/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.entry.base.ejb;

import com.topcoder.timetracker.entry.base.EntryManager;

import javax.ejb.EJBLocalObject;


/**
 * <p>
 * Local interface for EntitySessionBean. It contains exactly the same methods as EntityManager interface.
 * </p>
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety is dependent on the container.
 * </p>
 *
 * @author bendlund, TCSDEVELOPER
 * @version 3.2
  */
public interface EntryLocalObject extends EntryManager, EJBLocalObject {
}
