/*
 * Copyright (c) 2006, TopCoder, Inc. All rights reserved.
 */
package com.topcoder.timetracker.common;

import com.topcoder.search.builder.filter.Filter;

/**
 * <p>
 * This interface defines the necessary methods that a MileageRate DAO should support. Create, Retrieve, Update,
 * Delete and Enumerate (CRUDE) methods are provided. There is also a search method that utilizes Filter classes
 * from the Search Builder 1.2 component.
 * </p>
 * <p>
 * Thread Safety: - Implementations need not necessarily be thread safe. Each implementation should specify whether
 * it is thread-safe or not. The application should pick the correct implementation for it's requirements.
 * </p>
 *
 * @author TheCois
 * @author TheCois
 * @version 2.0
 */
public interface MileageRateDAO {

    /**
     * <p>
     * This is a constant for a search filter field name for the Company Id which a MileageRate belongs to.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the MileageRateDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchMileageRates method.
     * </p>
     *
     */
    String SEARCH_COMPANY_ID = "search_company_id";

    /**
     * <p>
     * This is a constant for a search filter field name for the Description of the MileageRate.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the MileageRateDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchMileageRates method.
     * </p>
     *
     */
    String SEARCH_DESCRIPTION = "search_description";

    /**
     * <p>
     * This is a constant for a search filter field name for the Mileage Rate's Date of Creation.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the MileageRateDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchMileageRates method.
     * </p>
     *
     */
    String SEARCH_CREATED_DATE = "search_created_date";

    /**
     * <p>
     * This is a constant for a search filter field name for the Mileage Rate's User Creator.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the MileageRateDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchMileageRates method.
     * </p>
     *
     */
    String SEARCH_CREATED_USER = "search_created_user";

    /**
     * <p>
     * This is a constant for a search filter field name for the Mileage Rate's Last Date of Modification.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the MileageRateDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchMileageRates method.
     * </p>
     *
     */
    String SEARCH_MODIFICATION_DATE = "search_modification_date";

    /**
     * <p>
     * This is a constant for a search filter field name for the Mileage Rate's Last User of Modification.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the MileageRateDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchMileageRates method.
     * </p>
     *
     */
    String SEARCH_MODIFICATION_USER = "search_modification_user";

    /**
     * <p>
     * Creates a datastore entry for the given Mileage Rate. An id is automatically generated by the DAO and
     * assigned to the Email. The MileageRate is also considered to have been created by the specified username.
     * </p>
     *
     *
     *
     * @return The same mileageRate Object, with an assigned id, creationDate, modificationDate, creationUser and
     *         modificationUser assigned appropriately.
     * @param mileageRate The mileageRate to create within the datastore.
     * @param username The username of the user responsible for creating the MileageRate entry within the
     *        datastore.
     * @throws IllegalArgumentException if the mileageRate or username is null, or if username is an empty String.
     * @throws MileageRateDAOException if a problem occurs while accessing the datastore.
     */
    MileageRate createMileageRate(MileageRate mileageRate, String username) throws MileageRateDAOException;

    /**
     * <p>
     * Retrieves a MileageRate from the datastore with the provided id. If no MileageRate with that id exists, then
     * a null is returned.
     * </p>
     *
     *
     *
     * @return the Mileage rate.
     * @param id The id of the MileageRate to retrieve from the datastore.
     * @throws IllegalArgumentException if id is <=0
     * @throws MileageRateDAOException if a problem occurs while accessing the datastore.
     */
    MileageRate retrieveMileageRate(long id) throws MileageRateDAOException;

    /**
     * <p>
     * Updates the given MileageRate in the data store. The MileageRate is considered to have been modified by the
     * specified username.
     * </p>
     *
     *
     *
     * @param mileageRate The MileageRate entity to modify.
     * @param username The username of the user responsible for performing the update.
     * @throws IllegalArgumentException if the mileageRate is null, or the username is null, or the username is an
     *         empty String.
     * @throws MileageRateDAOException if a problem occurs while accessing the datastore.
     * @throws MileageRateNotFoundException if the MileageRate to update was not found in the data store.
     */
    void updateMileageRate(MileageRate mileageRate, String username) throws MileageRateDAOException,
            MileageRateNotFoundException;

    /**
     * <p>
     * Removes the specified MileageRate from the data store.
     * </p>
     *
     *
     *
     * @param mileageRate The mileageRate to delete.
     * @throws IllegalArgumentException if the mileageRate is null.
     * @throws MileageRateDAOException if a problem occurs while accessing the datastore.
     * @throws MileageRateNotFoundException if the MileageRate to delete was not found in the data store.
     */
    void deleteMileageRate(MileageRate mileageRate) throws MileageRateDAOException, MileageRateNotFoundException;

    /**
     * <p>
     * Enumerates all the MileageRates that are present within the data store.
     * </p>
     *
     *
     *
     * @return A list of all the MileageRates within the data store.
     * @throws MileageRateDAOException if a problem occurs while accessing the datastore.
     */
    MileageRate[] listMileageRates() throws MileageRateDAOException;

    /**
     * <p>
     * Returns a list of all the RejectReasons within the datastore that satisfy the filters that are provided. The
     * filters are defined using classes from the Search Builder v1.2 component and com.topcoder.timetracker.
     * common.search package.
     * </p>
     *
     *
     *
     * @return A list of RejectReasons that satisfy the search criterion.
     * @param filter The filter that is used as criterion to facilitate the search..
     * @throws IllegalArgumentException if the filter is null.
     * @throws MileageRateDAOException if a problem occurs while accessing the datastore.
     */
    MileageRate[] searchMileageRates(Filter filter) throws MileageRateDAOException;
}
