/*
 * Copyright (c) 2006, TopCoder, Inc. All rights reserved.
 */
package com.topcoder.timetracker.common;

import com.topcoder.search.builder.filter.Filter;

/**
 * <p>
 * This interface defines the necessary methods that a RejectReason DAO should support. Create, Retrieve, Update,
 * Delete and Enumerate (CRUDE) methods are provided. There is also a search method that utilizes Filter classes
 * from the Search Builder 1.2 component.
 * </p>
 * <p>
 * Thread Safety: - Implementations need not necessarily be thread safe. Each implementation should specify whether
 * it is thread-safe or not. The application should pick the correct implementation for it's requirements.
 * </p>
 *
 * @author ShindouHikaru
 * @author kr00tki
 * @version 2.0
 */
public interface RejectReasonDAO {

    /**
     * <p>
     * This is a constant for a search filter field name for the Company Id which a RejectReason belongs to.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the RejectReasonDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchRejectReasons method.
     * </p>
     *
     */
    String SEARCH_COMPANY_ID = "search_company_id";

    /**
     * <p>
     * This is a constant for a search filter field name for the Description of the RejectReason.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the RejectReasonDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchRejectReasons method.
     * </p>
     *
     */
    String SEARCH_DESCRIPTION = "search_description";

    /**
     * <p>
     * This is a constant for a search filter field name for the Active Status of the RejectReason.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the RejectReasonDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchRejectReasons method.
     * </p>
     *
     */
    String SEARCH_ACTIVE_STATUS = "search_active_status";

    /**
     * <p>
     * This is a constant for a search filter field name for the Reject Reason's Date of Creation.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the RejectReasonDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchRejectReasons method.
     * </p>
     *
     */
    String SEARCH_CREATED_DATE = "search_created_date";

    /**
     * <p>
     * This is a constant for a search filter field name for the Reject Reason's User Creator.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the RejectReasonDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchRejectReasons method.
     * </p>
     *
     */
    String SEARCH_CREATED_USER = "search_created_user";

    /**
     * <p>
     * This is a constant for a search filter field name for the Reject Reason's Last Date of Modification.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the RejectReasonDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchRejectReasons method.
     * </p>
     *
     */
    String SEARCH_MODIFICATION_DATE = "search_modification_date";

    /**
     * <p>
     * This is a constant for a search filter field name for the Reject Reason's Last User of Modification.
     * </p>
     * <p>
     * Filters from the Search Builder component may use this constant when building their search parameters.
     * Implementations of the RejectReasonDAO interface should be able to recognize search filters bearing the
     * provided constant and adjust their searches according to the searchRejectReasons method.
     * </p>
     *
     */
    String SEARCH_MODIFICATION_USER = "search_modification_user";

    /**
     * <p>
     * Creates a datastore entry for the given Reject Reason. An id is automatically generated by the DAO and
     * assigned to the reason. The RejectReason is also considered to have been created by the specified username.
     * </p>
     *
     *
     *
     * @return The same rejectReason Object, with an assigned id, creationDate, modificationDate, creationUser and
     *         modificationUser assigned appropriately.
     * @param rejectReason The rejectReason to create within the datastore.
     * @param username The username of the user responsible for creating the RejectReason entry within the
     *        datastore.
     * @throws IllegalArgumentException if the rejectReason or username is null, or if username is an empty String.
     * @throws RejectReasonDAOException if a problem occurs while accessing the data store.
     */
    RejectReason createRejectReason(RejectReason rejectReason, String username) throws RejectReasonDAOException;

    /**
     * <p>
     * Retrieves a RejectReason from the datastore with the provided id. If no RejectReason with that id exists,
     * then a null is returned.
     * </p>
     *
     *
     *
     * @param id The id of the RejectReason to retrieve from the datastore.
     * @return the RejectReason object or null, if not found.
     * @throws IllegalArgumentException if id is <=0
     * @throws RejectReasonDAOException if a problem occurs while accessing the data store.
     */
    RejectReason retrieveRejectReason(long id) throws RejectReasonDAOException;

    /**
     * <p>
     * Updates the given RejectReason in the data store. The RejectReason is considered to have been modified by
     * the specified username.
     * </p>
     *
     *
     *
     * @param rejectReason The RejectReason entity to modify.
     * @param username The username of the user responsible for performing the update.
     * @throws IllegalArgumentException if the rejectReason is null, or the username is null, or the username is an
     *         empty String.
     * @throws RejectReasonDAOException if a problem occurs while accessing the data store.
     * @throws RejectReasonNotFoundException if the RejectReason to update was not found in the data store.
     */
    void updateRejectReason(RejectReason rejectReason, String username) throws RejectReasonDAOException,
            RejectReasonNotFoundException;

    /**
     * <p>
     * Removes the specified RejectReason from the data store.
     * </p>
     *
     *
     *
     * @param rejectReason The rejectReason to delete.
     * @throws IllegalArgumentException if the rejectReason is null.
     * @throws RejectReasonDAOException if a problem occurs while accessing the data store.
     * @throws RejectReasonNotFoundException if the RejectReason to delete was not found in the data store.
     */
    void deleteRejectReason(RejectReason rejectReason) throws RejectReasonDAOException,
            RejectReasonNotFoundException;

    /**
     * <p>
     * Enumerates all the RejectReasons that are present within the data store.
     * </p>
     *
     *
     *
     * @return A list of all the RejectReasons within the data store.
     * @throws RejectReasonDAOException if a problem occurs while accessing the data store.
     */
    RejectReason[] listRejectReasons() throws RejectReasonDAOException;

    /**
     * <p>
     * Returns a list of all the RejectReasons within the datastore that satisfy the filters that are provided. The
     * filters are defined using classes from the Search Builder v1.2 component and com.topcoder.timetracker.
     * common.search package.
     * </p>
     *
     *
     *
     * @return A list of RejectReasons that satisfy the search criterion.
     * @param filter The filter that is used as criterion to facilitate the search..
     * @throws IllegalArgumentException if the filter is null.
     * @throws RejectReasonDAOException if a problem occurs while accessing the data store.
     */
    RejectReason[] searchRejectReasons(Filter filter) throws RejectReasonDAOException;
}
