/*
 * Copyright (C) 2009 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.service.studio.ejb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * This class represents the "document_not_found_fault" element in WSDL. It's
 * contained in the related exception-message class, it's the fault bean. It was
 * generated by JBoss tools and I changed the name and other little changes.
 * </p>
 *
 * <p>
 * This class is not thread safe because it's highly mutable
 * </p>
 *
 * @author fabrizyo, TCSDEVELOPER
 * @version 1.0
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "documentIdNotFound" })
@XmlRootElement(name = "document_not_found_fault")
public class DocumentNotFoundFault {
    /**
     * <p>
     * Represents the document Not Found in the exception. I updated the WSDL,
     * now it's long.
     * </p>
     */
    @XmlElement(name = "document_not_found", required = true)
    private long documentIdNotFound;

    /**
     * <p>
     * This is the default constructor. It does nothing.
     * </p>
     */
    public DocumentNotFoundFault() {
    }

    /**
     * <p>
     * Gets the value of the documentIdNotFound property.
     * </p>
     *
     * @return the value of the documentIdNotFound property.
     */
    public long getDocumentIdNotFound() {
        return documentIdNotFound;
    }

    /**
     * <p>
     * Sets the value of the documentIdNotFound property.
     * </p>
     *
     * @param documentIdNotFound the value to set
     */
    public void setDocumentIdNotFound(long documentIdNotFound) {
        this.documentIdNotFound = documentIdNotFound;
    }
}
