/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.project.ejb;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * <p>
 * This is the local home interface for the <code>ProjectWorkerUtility</code>.
 * </p>
 *
 * <p>
 * It contains only a single no-param create method that produces an instance of the
 * local interface. It is used to obtain a handle to the Stateless SessionBean.
 * </p>
 *
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety
 * is dependent on the container.
 * </p>
 *
 * @author ShindouHikaru, bendlund, TCSDEVELOPER
 * @version 3.2
 */
public interface ProjectWorkerUtilityLocalHome extends EJBLocalHome {
    /**
     * <p>
     * Creates an instance of <code>ProjectWorkerUtilityLocal</code>, which is a
     * handle to the <code>SessionBean</code>.
     * </p>
     *
     * @return an instance of <code>ProjectWorkerLocal</code>
     * @throws CreateException if the local object or session bean couldn't be created
     */
    public ProjectWorkerUtilityLocal create() throws CreateException;
}
