/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.project.ejb;

import com.topcoder.timetracker.project.ProjectManagerUtility;
import javax.ejb.EJBLocalObject;

/**
 * <p>
 * This is the local interface for <code>ProjectManagerUtility</code>.
 * </p>
 *
 * <p>
 * It contains exactly the same methods as <code>ProjectManagerUtility</code> interface.
 * </p>
 *
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety
 * is dependent on the container.
 * </p>
 *
 * @author ShindouHikaru, bendlund, TCSDEVELOPER
 * @version 3.2
 */
public interface ProjectManagerUtilityLocal extends ProjectManagerUtility, EJBLocalObject {
}