/*
 * Copyright (C) 2006 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.project.accuracytests.persistence;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.util.Date;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

import com.topcoder.timetracker.project.accuracytests.Helper;
import com.topcoder.timetracker.project.persistence.DatabaseSearchUtility;
import com.topcoder.timetracker.project.searchfilters.BinaryOperation;
import com.topcoder.timetracker.project.searchfilters.BinaryOperationFilter;
import com.topcoder.timetracker.project.searchfilters.CompareOperation;
import com.topcoder.timetracker.project.searchfilters.Filter;
import com.topcoder.timetracker.project.searchfilters.MultiValueFilter;
import com.topcoder.timetracker.project.searchfilters.NotFilter;
import com.topcoder.timetracker.project.searchfilters.ValueFilter;

/**
 * The class <code>DatabaseSearchUtilityAccuracytest</code> contains tests for the class
 * {@link <code>DatabaseSearchUtility</code>}.
 * @author FireIce, costty
 * @version 2.0
 */
public class DatabaseSearchUtilityAccuracytest extends TestCase {
    /**
     * The SQL statement to insert a client.
     */
    private static final String SQL_INS_CLIENT = "INSERT INTO client VALUES (?, ?, ?, ?, ?, ?, ?)";

    /**
     * The DatabaseSearchUtility instance to test against.
     */
    private DatabaseSearchUtility utility = null;

    /**
     * Represents the connection.
     */
    private Connection connection;

    /**
     * The prepared statement generated by the utility.
     */
    private PreparedStatement pstmt = null;

    /**
     * The resultset obtained by executing the prepared statement.
     */
    private ResultSet rs = null;

    /**
     * The search filter to apply.
     */
    private Filter filter = null;

    /**
     * accuracy test for constructor.
     * @throws Exception
     *             to JUnit
     */
    public void testCtorAccuracy() throws Exception {
        new DatabaseSearchUtility(Helper.getConnection(),
                "com.topcoder.timetracker.project.accuraytests.DatabaseSearchUtility.clients");
    }

    /**
     * accuracy test for prepareSearchStatement method.
     */
    public void testPrepareSearchStatementAccuracy() throws Exception {
        filter = new ValueFilter(CompareOperation.LIKE, "Creation User", "creation%");
        pstmt = utility.prepareSearchStatement(filter);
        rs = pstmt.executeQuery();
        assertTrue("Prepares an incorrect statement", rs.next());
        assertEquals("query returned incorrect", 1, rs.getInt(1));
        assertFalse("Prepares an incorrect statement", rs.next());
        rs.close();
        pstmt.close();

        filter = new ValueFilter(CompareOperation.LIKE, "Creation User", "mock%");
        pstmt = utility.prepareSearchStatement(filter);
        rs = pstmt.executeQuery();
        assertFalse("Prepares an incorrect statement", rs.next());
        rs.close();
        pstmt.close();

        filter = new MultiValueFilter("Creation User", new Object[] {"creationUser", "modificationUser"});
        pstmt = utility.prepareSearchStatement(filter);
        rs = pstmt.executeQuery();
        assertTrue("Prepares an incorrect statement", rs.next());
        assertEquals("query returned incorrect", 1, rs.getInt(1));
        assertFalse("Prepares an incorrect statement", rs.next());
        rs.close();
        pstmt.close();

        Filter leftOperand = new ValueFilter(CompareOperation.EQUAL, "Name", "name");
        Filter rightOperand = new ValueFilter(CompareOperation.EQUAL, "Creation User", "creationUser");

        filter = new BinaryOperationFilter(BinaryOperation.AND, leftOperand, rightOperand);
        pstmt = utility.prepareSearchStatement(filter);
        rs = pstmt.executeQuery();
        assertTrue("Prepares an incorrect statement", rs.next());
        assertEquals("query returned incorrect", 1, rs.getInt(1));
        assertFalse("Prepares an incorrect statement", rs.next());
        rs.close();
        pstmt.close();

        Filter operand = new ValueFilter(CompareOperation.EQUAL, "Name", "abc");
        filter = new NotFilter(operand);
        pstmt = utility.prepareSearchStatement(filter);
        rs = pstmt.executeQuery();
        assertTrue("Prepares an incorrect statement", rs.next());
        assertEquals("query returned incorrect", 1, rs.getInt(1));
        assertFalse("Prepares an incorrect statement", rs.next());
        rs.close();
        pstmt.close();
    }

    /**
     * Prepares a DatabaseSearchUtility instance for testing. Also adds a client to the database so that it can be
     * selected by the generated prepared statement. The client has the name "name" and creation user "creationUser".
     * @throws Exception
     *             if any unexpected exception occurs.
     */
    protected void setUp() throws Exception {
        Helper.addConfig();
        Helper.clearTables();
        // prepare the connection and search utility
        connection = Helper.getConnection();
        utility = new DatabaseSearchUtility(connection, Helper.DB_SEARCH_UTILITY_CLIENTS);

        // add a client to the database
        Date date = new Date();
        PreparedStatement pstmt = connection.prepareStatement(SQL_INS_CLIENT);

        pstmt.setInt(1, 1);
        pstmt.setInt(2, 1);
        pstmt.setString(3, "name");
        pstmt.setTimestamp(4, new Timestamp(date.getTime()));
        pstmt.setString(5, "creationUser");
        pstmt.setTimestamp(6, new Timestamp(date.getTime()));
        pstmt.setString(7, "modificationUser");

        pstmt.executeUpdate();
        pstmt.close();
    }

    /**
     * Clears all the namespaces and database resources.
     * @throws Exception
     *             if any unexpected exception occurs.
     */
    protected void tearDown() throws Exception {
        Helper.clearTables();
        Helper.clearConfig();
        if (connection != null) {
            connection.close();
        }
    }

    /**
     * Aggragates all tests in this class.
     * @return test suite aggragating all tests.
     */
    public static Test suite() {
        return new TestSuite(DatabaseSearchUtilityAccuracytest.class);
    }
}
