package com.topcoder.controlpanel.clientassociations.dao.hibernate;
// Generated 2007-12-8 12:51:43 by Hibernate Tools 3.2.0.CR1



/**
 * CompClient generated by hbm2java
 */
public class CompClient  implements java.io.Serializable {


     private CompClientPK comp_id;
     private Client client;

    public CompClient() {
    }

	
    public CompClient(CompClientPK comp_id) {
        this.comp_id = comp_id;
    }
    public CompClient(CompClientPK comp_id, Client client) {
       this.comp_id = comp_id;
       this.client = client;
    }
   
    public CompClientPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(CompClientPK comp_id) {
        this.comp_id = comp_id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }




}


