INSERT INTO log_entry_type (id, text) VALUES (1, 'ERROR IN APPLICATIONS LOGIC !!! Passed test for target "{0}" from URL {1} for game {2} and domain {3} - SHOULD HAVE NOT REACH THIS FORWARD!!!');
INSERT INTO log_entry_type (id, text) VALUES (2, 'ERROR IN APPLICATIONS LOGIC - SHOULD NOT REACH THAT FORWARD');
INSERT INTO log_entry_type (id, text) VALUES (3, 'ERROR IN APPLICATIONS LOGIC. Presented with Main Home page - SHOULD NOT REACH THIS FORWARD !!!');
INSERT INTO log_entry_type (id, text) VALUES (4, '[TESTING MODE] presented with JIGSAW Game Win puzzle for game {0} and slot {1}');
INSERT INTO log_entry_type (id, text) VALUES (5, '[TESTING MODE] presented with SLIDING TILE Game Win puzzle for game {0} and slot {1}');
INSERT INTO log_entry_type (id, text) VALUES (6, '[TESTING MODE] submitted solution for Game Win puzzle for game {0} and slot {1}');
INSERT INTO log_entry_type (id, text) VALUES (7, 'accepted game rules and registered to game {0}');
INSERT INTO log_entry_type (id, text) VALUES (8, 'attempted to confirm and place a new bid for game {0}, block {1}, auction {2} with domain {3}, image {4}, max bid amount {5} without account approval by Administrator');
INSERT INTO log_entry_type (id, text) VALUES (9, 'attempted to confirm and update bid for game {0}, block {1}, auction {2}, bid {3} with domain {4}, image {5}, max bid amount {6} without account approval by Administrator');
INSERT INTO log_entry_type (id, text) VALUES (10, 'attempted to login as {0} while already being logged to server');
INSERT INTO log_entry_type (id, text) VALUES (11, 'attempted to place a new bid for game {0}, block {1}, auction {2} with domain {3}, image {4}, max bid amount {5} without SPONSOR role assigned');
INSERT INTO log_entry_type (id, text) VALUES (12, 'attempted to register to game {0} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (13, 'attempted to replace the target for game {0}, slot {1} and sequence number {2} with text ''{3}'' and URL {4} without ADMIN role assigned');
INSERT INTO log_entry_type (id, text) VALUES (14, 'attempted to start game play for game {0} and domain {1} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (15, 'attempted to submit Place New Bid form for confirmation for game {0}, block {1}, auction {2} with domain {3}, image {4}, max bid amount {5} without SPONSOR role assigned');
INSERT INTO log_entry_type (id, text) VALUES (16, 'attempted to submit Place New Bid form for game {0}, block {1}, auction {2} with domain {3}, image {4}, max bid amount {5} without account approval by Administrator');
INSERT INTO log_entry_type (id, text) VALUES (17, 'attempted to submit Update Bid form for confirmation for game {0}, block {1}, auction {2}, bid {3} with domain {4}, image {5}, max bid amount {6} without SPONSOR role assigned');
INSERT INTO log_entry_type (id, text) VALUES (18, 'attempted to submit Update Bid form for game {0}, block {1}, auction {2}, bid {3} with domain {4}, image {5}, max bid amount {6} without account approval by Administrator');
INSERT INTO log_entry_type (id, text) VALUES (19, 'attempted to submit solution for Game Win puzzle for game {0} and slot {1} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (20, 'attempted to submit the Game Winner Registration form to server without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (21, 'attempted to test domain {0} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (22, 'attempted to test target "{0}" from URL {1} for game {2} and domain {3} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (23, 'attempted to unlock The Ball for game {0} and domain {1} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (24, 'attempted to unlock The Ball for game {0} and domain {1} without having all clues for domain found');
INSERT INTO log_entry_type (id, text) VALUES (25, 'attempted to update a bid for game {0}, block {1}, auction {2}, bid {3} with domain {4}, image {5}, max bid amount {6} without SPONSOR role assigned');
INSERT INTO log_entry_type (id, text) VALUES (26, 'attempted to view Active Games page without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (27, 'attempted to view Active Games page without logging to server');
INSERT INTO log_entry_type (id, text) VALUES (28, 'attempted to view Bidding FAQ page without SPONSOR role assigned');
INSERT INTO log_entry_type (id, text) VALUES (29, 'attempted to view Game Registration page for game {0} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (30, 'attempted to view Game Win puzzle for game {0} and domain {1} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (31, 'attempted to view Home page without any of supported roles assigned');
INSERT INTO log_entry_type (id, text) VALUES (32, 'attempted to view Open Auctions page without SPONSOR role assigned');
INSERT INTO log_entry_type (id, text) VALUES (33, 'attempted to view Overall Games Report without ADMIN role assigned');
INSERT INTO log_entry_type (id, text) VALUES (34, 'attempted to view Overall Player Report without ADMIN role assigned');
INSERT INTO log_entry_type (id, text) VALUES (35, 'attempted to view Place New Bid page for game {0}, block {1}, auction {2} without SPONSOR role assigned');
INSERT INTO log_entry_type (id, text) VALUES (36, 'attempted to view Place New Bid page for game {0}, block {1}, auction {2} without account approval by Administrator');
INSERT INTO log_entry_type (id, text) VALUES (37, 'attempted to view Player Account - Change Password page without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (38, 'attempted to view Player Account page without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (39, 'attempted to view Player FAQ page without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (40, 'attempted to view Player Home page without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (41, 'attempted to view Update Bid page for game {0}, block {1}, auction {2}, bid {3} without SPONSOR role assigned');
INSERT INTO log_entry_type (id, text) VALUES (42, 'attempted to view Update Bid page for game {0}, block {1}, auction {2}, bid {3} without account approval by Administrator');
INSERT INTO log_entry_type (id, text) VALUES (43, 'attempted to view brainteaser for game {0} and domain {1} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (44, 'attempted to view leader board for game {0} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (45, 'attempted to view list of active games for domain {0} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (46, 'attempted to view list of unlocked domains for game {0} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (47, 'attempted to view list of upcoming domains for game {0} without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (48, 'attempted to view the list of registered games without PLAYER role assigned');
INSERT INTO log_entry_type (id, text) VALUES (49, 'confirmed and updated a bid for game {0}, block {1}, auction {2}, bid {3} with max bid amount {4}');
INSERT INTO log_entry_type (id, text) VALUES (50, 'confrimed and placed a new bid for game {0}, auction {1} with image {2}, max bid amount {3}');
INSERT INTO log_entry_type (id, text) VALUES (51, 'failed to confirm and place a new bid for game {0}, block {1}, auction {2} with domain {3}, image {4}, max bid amount {5} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (52, 'failed to confirm and update bid for game {0}, block {1}, auction {2}, bid {3} with domain {4}, image {5}, max bid amount {6} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (53, 'failed to login as {0} due to invalid credentials');
INSERT INTO log_entry_type (id, text) VALUES (54, 'failed to login as {0} due to unknown profile');
INSERT INTO log_entry_type (id, text) VALUES (55, 'failed to open Active Games page due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (56, 'failed to open Open Auctions page due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (57, 'failed to open Place New Bid page for game {0}, block {1}, auction {2} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (58, 'failed to open Player Account - Change Password page due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (59, 'failed to open Player Account page due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (60, 'failed to open Player FAQ page due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (61, 'failed to open Sponsor FAQ page due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (62, 'failed to open Update Bid page for game {0}, block {1}, auction {2}, bid {3} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (63, 'failed to pass test for target "{0}" from URL {1} for game {2} and domain {3}');
INSERT INTO log_entry_type (id, text) VALUES (64, 'failed to pass test for target "{0}" from URL {1} for game {2} and domain {3} due to incorrect URL');
INSERT INTO log_entry_type (id, text) VALUES (65, 'failed to pass the validation for the Login form with username {0}');
INSERT INTO log_entry_type (id, text) VALUES (66, 'failed to pass the validation for the Place New Bid form with game {0}, block {1}, auction {2} with domain {3}, image {4}, max bid amount {5}');
INSERT INTO log_entry_type (id, text) VALUES (67, 'failed to pass the validation for the Retrieve Password form with email address {0}');
INSERT INTO log_entry_type (id, text) VALUES (68, 'failed to pass the validation for the Update Bid form with game {0}, block {1}, auction {2}, bid {3} with domain {4}, image {5}, max bid amount {6}');
INSERT INTO log_entry_type (id, text) VALUES (69, 'failed to pass the validation for the confirmed Place New Bid form with game {0}, block {1}, auction {2} with domain {3}, image {4}, max bid amount {5}');
INSERT INTO log_entry_type (id, text) VALUES (70, 'failed to pass the validation for the confirmed Update Bid form with game {0}, block {1}, auction {2}, bid {3} with domain {4}, image {5}, max bid amount {6}');
INSERT INTO log_entry_type (id, text) VALUES (71, 'failed to poll the messages with timestamp {0} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (72, 'failed to register to game {0} due to not accepting the game rules');
INSERT INTO log_entry_type (id, text) VALUES (73, 'failed to register to game {0} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (74, 'failed to replace the target for game {0}, slot {1} and sequence number {2} with text "{3}" and URL {4} as the page at specified URL could not be retrieved');
INSERT INTO log_entry_type (id, text) VALUES (75, 'failed to replace the target for game {0}, slot {1} and sequence number {2} with text "{3}" and URL {4} as the target is not valid');
INSERT INTO log_entry_type (id, text) VALUES (76, 'failed to replace the target for game {0}, slot {1} and sequence number {2} with text ''{3}'' and URL {4} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (77, 'failed to retrieve the password due to unknown email address {0}');
INSERT INTO log_entry_type (id, text) VALUES (78, 'failed to solve Game Win puzzle for game {0} and slot {1} correctly');
INSERT INTO log_entry_type (id, text) VALUES (79, 'failed to solve Game Win puzzle for game {0} and slot {1} within the configured period');
INSERT INTO log_entry_type (id, text) VALUES (80, 'failed to submit Place New Bid form for game {0}, block {1}, auction {2} with domain {3}, image {4}, max bid amount {5} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (81, 'failed to submit Update Bid form for game {0}, block {1}, auction {2}, bid {3} with domain {4}, image {5}, max bid amount {6} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (82, 'failed to test domain {0} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (83, 'failed to test puzzle solution for game {0} and slot {1} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (84, 'failed to test target "{0}" from URL {1} for game {2} and domain {3} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (85, 'failed to unlock The Ball for game {0} and domain {1} as the game is no longer active');
INSERT INTO log_entry_type (id, text) VALUES (86, 'failed to unlock The Ball for game {0} and domain {1} due to incorrect keys [{2}] submitted');
INSERT INTO log_entry_type (id, text) VALUES (87, 'failed to unlock The Ball for game {0} and domain {1} due to incorrect keys [{2}] submitted and has reached the limit of failed attempts');
INSERT INTO log_entry_type (id, text) VALUES (88, 'failed to unlock The Ball for game {0} and domain {1} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (89, 'failed to view Game Registration page for game {0} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (90, 'failed to view Game Win puzzle for game {0} and domain {1} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (91, 'failed to view Home page due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (92, 'failed to view Overall Games Report due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (93, 'failed to view Overall Player Report due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (94, 'failed to view Player Home page due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (95, 'failed to view brainteaser for game {0} and domain {1} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (96, 'failed to view leader board for game {0} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (97, 'failed to view leader board for game {0} due to unexpected error');
INSERT INTO log_entry_type (id, text) VALUES (98, 'failed to view list of active games for domain {0} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (99, 'failed to view list of registered games due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (100, 'failed to view list of unlocked domains for game {0} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (101, 'failed to view list of upcoming domains for game {0} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (102, 'failed to view list registered games due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (103, 'got the time left for solving the puzzle for game {0} and slot {1}');
INSERT INTO log_entry_type (id, text) VALUES (104, 'had failed to pass the validation for the Game Winner Registration form');
INSERT INTO log_entry_type (id, text) VALUES (105, 'had failed to start game play for game {0} and domain {1} due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (106, 'had failed to submit the Game Winner Registration form to server due to session timeout or is not authenticated to server');
INSERT INTO log_entry_type (id, text) VALUES (107, 'has submitted Game Winner Registration form to the server');
INSERT INTO log_entry_type (id, text) VALUES (108, 'is not registered to game {0} for domain {1} while attempting to unlock The Ball');
INSERT INTO log_entry_type (id, text) VALUES (109, 'is not registered to game {0} for domain {1} while attempting to view Game Win puzzle');
INSERT INTO log_entry_type (id, text) VALUES (110, 'is not registered to game {0} for domain {1} while attempting to view brainteaser');
INSERT INTO log_entry_type (id, text) VALUES (111, 'is not registered to game {0} while attempting to submit solution for Game Win puzzle');
INSERT INTO log_entry_type (id, text) VALUES (112, 'is not registered to game {0} while attempting to test target "{1}" from URL {2} for domain {3}');
INSERT INTO log_entry_type (id, text) VALUES (113, 'logged in');
INSERT INTO log_entry_type (id, text) VALUES (114, 'passed test for target "{0}" from URL {1} for game {2} and domain {3} and found The Ball');
INSERT INTO log_entry_type (id, text) VALUES (115, 'passed test for target "{0}" from URL {1} for game {2} and domain {3} and found a key for domain');
INSERT INTO log_entry_type (id, text) VALUES (116, 'passed test for target "{0}" from URL {1} for game {2} and domain {3} and has to find next target in sequence');
INSERT INTO log_entry_type (id, text) VALUES (117, 'presented with Active Games page');
INSERT INTO log_entry_type (id, text) VALUES (118, 'presented with Admin Home page');
INSERT INTO log_entry_type (id, text) VALUES (119, 'presented with Bidding FAQ page');
INSERT INTO log_entry_type (id, text) VALUES (120, 'presented with Game Registration page for game {0}');
INSERT INTO log_entry_type (id, text) VALUES (121, 'presented with Game Win puzzle for game {0} and domain {1}');
INSERT INTO log_entry_type (id, text) VALUES (122, 'presented with Main page');
INSERT INTO log_entry_type (id, text) VALUES (123, 'presented with Overall Games Report');
INSERT INTO log_entry_type (id, text) VALUES (124, 'presented with Overall Player Report');
INSERT INTO log_entry_type (id, text) VALUES (125, 'presented with Place New Bid page for game {0}, block {1}, auction {2}');
INSERT INTO log_entry_type (id, text) VALUES (126, 'presented with Player Account - Change Password page');
INSERT INTO log_entry_type (id, text) VALUES (127, 'presented with Player Account page');
INSERT INTO log_entry_type (id, text) VALUES (128, 'presented with Player FAQ page');
INSERT INTO log_entry_type (id, text) VALUES (129, 'presented with Player Home page');
INSERT INTO log_entry_type (id, text) VALUES (130, 'presented with Sponsor Home page');
INSERT INTO log_entry_type (id, text) VALUES (131, 'presented with Update Bid page for game {0}, block {1}, auction {2}, bid {3}');
INSERT INTO log_entry_type (id, text) VALUES (132, 'presented with brainteaser for game {0} and domain {1}');
INSERT INTO log_entry_type (id, text) VALUES (133, 'presented with details for game {0}');
INSERT INTO log_entry_type (id, text) VALUES (134, 'presented with leader board for game {0}');
INSERT INTO log_entry_type (id, text) VALUES (135, 'presented with list of active games for domain {0}');
INSERT INTO log_entry_type (id, text) VALUES (136, 'presented with list of games the player is registered to');
INSERT INTO log_entry_type (id, text) VALUES (137, 'presented with list of open auctions');
INSERT INTO log_entry_type (id, text) VALUES (138, 'presented with list of unlocked domains for game {0}');
INSERT INTO log_entry_type (id, text) VALUES (139, 'presented with list of upcoming domains for game {0}');
INSERT INTO log_entry_type (id, text) VALUES (140, 'replaced the target for game {0}, slot {1} and sequence number {2} with text "{3}" and URL {4}');
INSERT INTO log_entry_type (id, text) VALUES (141, 'resumed the game play for game {0} and domain {1} and has to find next target in sequence');
INSERT INTO log_entry_type (id, text) VALUES (142, 'resumed the game play for game {0} and domain {1} while already having all targets found and found The Ball');
INSERT INTO log_entry_type (id, text) VALUES (143, 'resumed the game play for game {0} and domain {1} while already having all targets found and found a key for domain');
INSERT INTO log_entry_type (id, text) VALUES (144, 'retrieved the password for email address {0}');
INSERT INTO log_entry_type (id, text) VALUES (145, 'solved Game Win puzzle for game {0} and slot {1} within the configured period and presented with Game Winner Registration form');
INSERT INTO log_entry_type (id, text) VALUES (146, 'starting the game play for game {0} and domain {1}');
INSERT INTO log_entry_type (id, text) VALUES (147, 'submitted Place New Bid form for confirmation for game {0}, block {1}, auction {2} with domain {3}, image {4}, max bid amount {5}');
INSERT INTO log_entry_type (id, text) VALUES (148, 'submitted Update Bid form for confirmation for game {0}, block {1}, auction {2}, bid {3} with domain {4}, image {5}, max bid amount {6}');
INSERT INTO log_entry_type (id, text) VALUES (149, 'tested domain {0}');
INSERT INTO log_entry_type (id, text) VALUES (150, 'unlocked The Ball for game {0} and domain {1} with keys [{2}]');
