INSERT INTO project_type_lu(project_type_id, name, description, create_user, create_date, modify_user, modify_date) VALUES(1, 'Component', 'Component', 'System', CURRENT, 'System', CURRENT);
INSERT INTO project_category_lu(project_category_id, project_type_id, name, description, create_user, create_date, modify_user, modify_date) VALUES(1, 1, 'Design', 'Design', 'System', CURRENT, 'System', CURRENT);
insert into project_status_lu values (1,"name","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into project values (1,1,1,"creation_user",CURRENT,"modify_user",CURRENT);
insert into phase_type_lu  values (1,"name","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into resource_role_lu values (1,1,"name","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into phase_status_lu values (1,"name","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into phase  values (1,1,1,1,CURRENT,CURRENT,CURRENT,CURRENT,CURRENT,1-2,"creation_user",CURRENT,"modify_user",CURRENT);
insert into resource  values (3,1,1,1,"creation_user",CURRENT,"modify_user",CURRENT);
insert into upload_status_lu values (1,"Active","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into upload_type_lu values (1,"Submission","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into upload_type_lu values (2,"Test Case","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into upload_type_lu values (3,"Final Fix","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into upload  values (1,1,3,1,1,"parameter","creation_user",CURRENT,"modify_user",CURRENT);
insert into upload  values (2,1,3,2,1,"parameter","creation_user",CURRENT,"modify_user",CURRENT);
insert into upload  values (3,1,3,3,1,"parameter","creation_user",CURRENT,"modify_user",CURRENT);
insert into submission_status_lu values (1,"name","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into submission  values (4,1,1,"creation_user",CURRENT,"modify_user",CURRENT);
insert into scorecard_type_lu values (1,"name","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into scorecard_status_lu values (1,"name","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into scorecard values (1,1,1,1,"name","version",0,100,"creation_user",CURRENT,"modify_user",CURRENT);
insert into review  values (1,3,4,1,1,100,"creation_user",CURRENT,"modify_user",CURRENT);
insert into comment_type_lu values (1,"Aggregation Review Comment","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into comment_type_lu values (2,"Submitter Comment","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into comment_type_lu values (3,"Final Review Comment","description","creation_user",CURRENT,"modify_user",CURRENT);
insert into review_comment values (1,3,1,1,"content","Approved",1,"creation_user",CURRENT,"modify_user",CURRENT);
insert into review_comment values (2,3,1,2,"content","Approved",1,"creation_user",CURRENT,"modify_user",CURRENT);
insert into review_comment values (3,3,1,3,"content","Approved",1,"creation_user",CURRENT,"modify_user",CURRENT);