-- clear tables
DROP TABLE client_project;
DROP TABLE project_expense;
DROP TABLE project_manager;
DROP TABLE project_time;
DROP TABLE project_worker;
DROP TABLE client;
DROP TABLE project;
DROP TABLE expense_entry;
DROP TABLE time_entry;
DROP TABLE user_account;
DROP TABLE company;
