/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.rejectreason.ejb;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;


/**
 * <p>
 * EJBLocalHome interface for the RejectReasonDAO. It contains only a single no-param create method that produces an
 * instance of the local interface. it is used to obtain a handle to the Stateless SessionBean.
 * </p>
 *
 * <p>
 * <b>Thread Safety:</b> Implementation will be generated by EJB container and thread-safety is dependent on the
 * container.
 * </p>
 *
 * @author wangqing, TCSDEVELOPER
 * @version 3.2
 */
public interface RejectReasonDAOLocalHome extends EJBLocalHome {
    /** The JNDI name for RejectReasonDAOLocalHome. */
    public static final String EJB_REF_HOME = "RejectReasonDAOLocalHome";

    /**
     * <p>
     * Creates an instance of RejectReasonDAOLocal, which is a handle to the SessionBean.
     * </p>
     *
     * @return an instance of RejectReasonDAOLocal.
     */
    public RejectReasonDAOLocal create() throws CreateException;
}
