/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.rejectreason.ejb;

import com.topcoder.timetracker.rejectreason.RejectEmailDAO;

import javax.ejb.EJBLocalObject;


/**
 * <p>
 * Local interface for RejectEmailDAO. It contains exactly the same methods as RejectEmailDAO interface.
 * </p>
 *
 * <p>
 * <b>Thread Safety:</b> Implementation will be generated by EJB container and thread-safety is dependent on the
 * container.
 * </p>
 *
 * @author wangqing, TCSDEVELOPER
 * @version 3.2
 */
public interface RejectEmailDAOLocal extends RejectEmailDAO, EJBLocalObject {
}
