INSERT INTO Users VALUES (300);
INSERT INTO Users VALUES (400);
INSERT INTO TimeEntries VALUES (500);
INSERT INTO ExpenseEntries VALUES (500);

INSERT INTO TimeEntries VALUES (0);
INSERT INTO TimeEntries VALUES (1);
INSERT INTO TimeEntries VALUES (2);
INSERT INTO ExpenseEntries VALUES (0);
INSERT INTO ExpenseEntries VALUES (1);
INSERT INTO ExpenseEntries VALUES (2);