
package com.topcoder.timetracker.project.ejb;
import com.topcoder.naming.jndiutility.JNDIUtils;
import com.topcoder.timetracker.project.ejb.ProjectManagerUtilityLocal;
import com.topcoder.util.config.ConfigManager;
/**
 * <p>
 * LocalHome interface for the ProjectManagerUtility.  It contains only a
 * single no-param create method that produces an instance of the 
 * local interface.  it is used to obtain a handle to the Stateless 
 * SessionBean.
 * </p>
 * <p>
 * Thread Safety:
 *  Implementation will be generated by EJB container and thread-safety
 * is dependent on the container.
 * </p>
 * 
 * @poseidon-object-id [I693c885bm1110ffc43d4m3719]
 */
public interface ProjectManagerUtilityLocalHome extends javax.ejb.EJBLocalHome {
/**
 * <p>
 * Creates an instance of ProjectManagerUtilityLocal, which is a 
 * handle to the SessionBean.
 * </p>
 * 
 * @poseidon-object-id [I693c885bm1110ffc43d4m3751]
 * @return an instance of ProjectManagerUtilityLocal
 * @throws CreateException if the local object or session bean couldn't be created
 */
    public com.topcoder.timetracker.project.ejb.ProjectManagerUtilityLocal create();
}


