
package com.topcoder.timetracker.project.ejb;
import com.topcoder.naming.jndiutility.JNDIUtils;
import com.topcoder.util.config.ConfigManager;
/**
 * <p>
 * Local interface for ProjectWorkerUtility.  It contains exactly the same methods
 * as ProjectWorkerUtility interface.
 * </p>
 * <p>
 * Thread Safety:
 *  Implementation will be generated by EJB container and thread-safety
 * is dependent on the container.
 * </p>
 * 
 * @poseidon-object-id [I693c885bm1110ffc43d4m53c5]
 */
public interface ProjectWorkerUtilityLocal extends javax.ejb.EJBLocalObject, com.topcoder.timetracker.project.ProjectWorkerUtility {
}


