
package com.topcoder.timetracker.project.ejb;
import com.topcoder.naming.jndiutility.JNDIUtils;
import com.topcoder.util.config.ConfigManager;
/**
 * <p>
 * Local interface for ProjectManagerUtility.  It contains exactly the same methods
 * as ProjectManagerUtility interface.
 * </p>
 * <p>
 * Thread Safety:
 *  Implementation will be generated by EJB container and thread-safety
 * is dependent on the container.
 * </p>
 * 
 * @poseidon-object-id [I693c885bm1110ffc43d4m35da]
 */
public interface ProjectManagerUtilityLocal extends com.topcoder.timetracker.project.ProjectManagerUtility, javax.ejb.EJBLocalObject {
}


