/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.user.j2ee;

import javax.ejb.EJBLocalHome;


/**
 * <p>
 * This is the local home interface for the <code>UserManager</code>.
 * </p>
 *
 * <p>
 * It contains only a single no-param create method that produces an instance of
 * the local interface.
 * </p>
 *
 * <p>
 * It is used to obtain a handle to the Stateless SessionBean.
 * </p>
 *
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety
 * is dependent on the container.
 * </p>
 *
 * @author ShindouHikaru, TCSDEVELOPER
 * @version 3.2
 */
public interface UserManagerLocalHome extends EJBLocalHome {
    /**
     * <p>
     * Creates an instance of <code>UserManagerLocal</code>, which is a
     * handle to the <code>SessionBean</code>.
     * </p>
     *
     * @return an instance of <code>UserManagerLocal</code>.
     */
    public UserManagerLocal create();
}
