/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.user.j2ee;

import javax.ejb.EJBLocalObject;
import com.topcoder.timetracker.user.UserManager;

/**
 * <p>
 * This is the local interface for <code>UserManager</code>.
 * </p>
 *
 * <p>
 * It contains exactly the same methods as <code>UserManager</code> interface.
 * </p>
 *
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety is dependent on the
 * container.
 * </p>
 *
 * @author ShindouHikaru, biotrail
 * @version 3.2
 */
public interface UserManagerLocal extends UserManager, EJBLocalObject {
}
