/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.user.j2ee;

import javax.ejb.EJBLocalObject;

import com.topcoder.timetracker.user.UserTypeManager;

/**
 * <p>
 * Local interface for <code>UserTypeManager</code>. It contains exactly the same methods as UserTypeManager
 * interface.
 * </p>
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety is dependent on the
 * container.
 * </p>
 *
 * @author George1, enefem21
 * @version 3.2.1
 * @since 3.2.1
 */
public interface UserTypeManagerLocal extends UserTypeManager, EJBLocalObject {
}
