/*
 * Copyright (C) 2009 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.service.studio;

import com.topcoder.service.studio.ejb.StatusNotFoundFault;
import com.topcoder.util.errorhandling.ExceptionData;

import javax.xml.ws.WebFault;

/**
 * <p>
 * This exception is thrown automatically by the web service interface when a
 * status is not found. It is related with "status_not_found_faultMsg" fault in
 * WSDL, but it contains only annotations about "status_not_found_fault" because
 * the messages are automatically constructed. It was generated by JBoss tools
 * and I changed the name, the inheritance and other changes.
 * </p>
 *
 * <p>
 * The constructors with StatusNotFoundFault and the getter are necessary for
 * the correct webservices serialization/deserialization. The other constructors
 * are added for the future implementations of the service interface.
 * </p>
 *
 * @author fabrizyo, TCSDEVELOPER
 * @version 1.0
 */
@WebFault(name = "status_not_found_fault", faultBean = "com.topcoder.service.studio.ejb.StatusNotFoundFault")
public class StatusNotFoundException extends StudioServiceException {
    /**
     * <p>
     * Represents the faultInfo, Java type that goes as soapenv:Fault detail
     * element.
     * </p>
     */
    private final StatusNotFoundFault faultInfo;

    /**
     * <p>
     * Represents the statusNotFound. I updated the WSDL, now it's an long. It
     * is retrieved from StatusNotFoundFault.
     * </p>
     */
    private final long statusIdNotFound;

    /**
     * <p>
     * Construct the exception. Call the super constructor,set the fault info
     * and set the statusIdNotFound from the faultInfo.
     * </p>
     *
     * @param message the message
     * @param faultInfo the fault info which contains the statusIdNotFound
     */
    public StatusNotFoundException(String message, StatusNotFoundFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
        this.statusIdNotFound = (faultInfo == null) ? -1 : faultInfo.getStatusIdNotFound();
    }

    /**
     * <p>
     * Construct the exception. Call the super constructor,set the fault info
     * and set the statusIdNotFound from the faultInfo.
     * </p>
     *
     * @param message the message
     * @param faultInfo the fault info which contains the statusIdNotFound
     * @param cause the cause
     */
    public StatusNotFoundException(String message, StatusNotFoundFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
        this.statusIdNotFound = (faultInfo == null) ? -1 : faultInfo.getStatusIdNotFound();
    }

    /**
     * <p>
     * Constructor with error message.
     * </p>
     *
     * @param message the error message
     * @param statusIdNotFound the status's id not found
     */
    public StatusNotFoundException(String message, long statusIdNotFound) {
        super(message);
        this.faultInfo = null;
        this.statusIdNotFound = statusIdNotFound;
    }

    /**
     * <p>
     * Constructor with error message and inner cause.
     * </p>
     *
     * @param message the error message
     * @param cause the cause of this exception
     * @param statusIdNotFound the status's id not found
     */
    public StatusNotFoundException(String message, Throwable cause, long statusIdNotFound) {
        super(message, cause);
        this.faultInfo = null;
        this.statusIdNotFound = statusIdNotFound;
    }

    /**
     * <p>
     * Constructor with error message and exception data.
     * </p>
     *
     * @param message the error message
     * @param data the exception data
     * @param statusIdNotFound the status's id not found
     */
    public StatusNotFoundException(String message, ExceptionData data, long statusIdNotFound) {
        super(message, data);
        this.faultInfo = null;
        this.statusIdNotFound = statusIdNotFound;
    }

    /**
     * <p>
     * Constructor with error message and inner cause and exception data.
     * </p>
     *
     * @param message the error message
     * @param cause the cause of this exception
     * @param data the exception data
     * @param statusIdNotFound the status's id not found
     */
    public StatusNotFoundException(String message, Throwable cause, ExceptionData data, long statusIdNotFound) {
        super(message, cause, data);
        this.faultInfo = null;
        this.statusIdNotFound = statusIdNotFound;
    }

    /**
     * <p>
     * Return the statusIdNotFound.
     * </p>
     *
     * @return the statusIdNotFound
     */
    public long getStatusIdNotFound() {
        return statusIdNotFound;
    }

    /**
     * <p>
     * Return the fault bean. This method is necessary for the
     * serialization/deserialization. it returns null if the constructors
     * without fault bean are used.
     * </p>
     *
     * @return returns fault bean
     */
    public StatusNotFoundFault getFaultInfo() {
        return faultInfo;
    }
}
