/*
 * Copyright (C) 2009 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.service.studio.ejb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * This class represents the "status_not_found_fault" element in WSDL. It's
 * contained in the related exception-message class, it's the fault bean. It was
 * generated by JBoss tools and I changed the name and other little changes.
 * </p>
 *
 * <p>
 * This class is not thread safe because it's highly mutable
 * </p>
 *
 * @author fabrizyo, TCSDEVELOPER
 * @version 1.0
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "statusIdNotFound" })
@XmlRootElement(name = "status_not_found_fault")
public class StatusNotFoundFault {
    /**
     * <p>
     * Represents the status Not Found in the exception. I updated the WSDL, now
     * it's long.
     * </p>
     * <p>
     */
    @XmlElement(name = "status_not_found", required = true)
    private long statusIdNotFound;

    /**
     * <p>
     * This is the default constructor. It does nothing.
     * </p>
     */
    public StatusNotFoundFault() {
    }

    /**
     * <p>
     * Gets the value of the statusIdNotFound property.
     * </p>
     *
     * @return the value of the statusIdNotFound property.
     */
    public long getStatusIdNotFound() {
        return statusIdNotFound;
    }

    /**
     * <p>
     * Sets the value of the statusIdNotFound property.
     * </p>
     *
     * @param statusIdNotFound the value to set
     */
    public void setStatusIdNotFound(long statusIdNotFound) {
        this.statusIdNotFound = statusIdNotFound;
    }
}
