/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.client.ejb;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;


/**
 * <p>
 * LocalHome interface for the ClientUtility.  It contains only a single no-param create method that produces an
 * instance of the local interface.  it is used to obtain a handle to the Stateless SessionBean.
 * </p>
 *
 * <p>
 * Thread Safety: Implementation will be generated by EJB container and thread-safety is dependent on the container.
 * </p>
 *
 * @author TCSDESIGNER, TCSDEVELOPER
 * @version 3.2
 */
public interface ClientUtilityLocalHome extends EJBLocalHome {
    /**
     * <p>
     * Creates an instance of ClientUtilityLocal, which is a handle to the SessionBean.
     * </p>
     *
     * @return an instance of ClientUtilityLocal.
     *
     * @throws CreateException if a problem occurs while creating the object.
     */
    public ClientUtilityLocal create() throws CreateException;
}
