/*
 * Copyright (C) 2007 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.timetracker.client.ejb;

import javax.ejb.EJBLocalObject;

import com.topcoder.timetracker.client.ClientUtility;


/**
 * <p>
 * Local interface for ClientUtility.  It contains exactly the same methods as ClientUtility interface.
 * </p>
 *
 * <p>
 * <b>Thread Safety:</b> Implementation will be generated by EJB container and thread-safety is dependent on the
 * container.
 * </p>
 *
 * @author TCSDESIGNER, TCSDEVELOPER
 * @version 3.2
 */
public interface ClientUtilityLocal extends ClientUtility, EJBLocalObject {
}
