/// CSharpClass File "WebBrowserDocumentCompletedEventHandler.cs" generated by Poseidon for UML.
/// Poseidon for UML is developed by <A HREF="http://www.gentleware.com">Gentleware</A>.
/// Generated with <A HREF="http://jakarta.apache.org/velocity/">velocity</A> template engine.

 namespace Orpheus_Client_Logic_for_MSIE {
   namespace Orpheus {
     namespace Plugin {
       namespace InternetExplorer {
         namespace EventsManagers {
           namespace Handlers {

             ///  <summary>
             ///  <!--StartFragment-->This class is an implementation of the IExtensionEventHandler interface.
             ///  <p class="MsoNormal">It performs a request to the server, if needed, and gets a numeric value based on which it will direct the browser to a new page.</p>
             ///  <p><strong>Thread safety: </strong>This class has no state and is thread safe.</p>
             ///  <!--EndFragment-->             ///  </summary>
             public class WebBrowserDocumentCompletedEventHandler : Orpheus.Plugin.InternetExplorer.EventsManagers.IExtensionEventHandler {

               /// Attributes

               /// Attribute DefaultConfigurationNamespace
               /// <summary>
               /// <p>Default configuration namespace.</p>               /// </summary>
               public Orpheus.Plugin.InternetExplorer.EventsManagers.Handlers.WebBrowserDocumentCompletedEventHandler.string DefaultConfigurationNamespace = "Orpheus.Plugin.InternetExplorer.EventsManagers.Handlers";

               /// Attribute configurationNamespace
               /// <summary>
               /// <p>Represents the configuration namespace to use.</p>
               /// <p>Set in the constructor and not changed afterwards. Can not be null or empty.</p>
               /// <p></p>               /// </summary>
               private readonly string configurationNamespace = <<constructor>>;

               /// Operations

               /// Constructor WebBrowserDocumentCompletedEventHandler
               /// <summary>
               /// <p>Constructor.</p>
               /// <p>Sets the default namespace to use.</p>
               /// <p></p>               /// </summary>
               public WebBrowserDocumentCompletedEventHandler() {
               }

               /// Constructor WebBrowserDocumentCompletedEventHandler
               /// <summary>
               /// <p>Constructor.</p>
               /// <p>Sets the field to the parameter value.</p>
               /// <p></p>               /// </summary>
               /// <exception>ArgumentNullException if parameter is null.</exception>
               /// <exception>ArgumentException if parameter is empty string.</exception>
               /// <param name='configurationNamespace'>Custom configuration namespace.</param>
               public WebBrowserDocumentCompletedEventHandler(string configurationNamespace) {
               }

               /// Operation HandleEvent
               /// <summary>
               /// <p>Handler method for the DocumentCompleted event.</p>
               /// <p><strong>Implementation details</strong></p>
               /// <p><!--StartFragment--></p>
               /// <ol type="1" start="1">
               /// <li style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; mso-list:l0 level1 lfo1;tab-stops:list .5in" class="MsoNormal">Get the URL of the current page: Gets the browser document from the browser and then the location <a href="http://www.aisto.com/roeder/dotnet/Default.aspx?Object=10" title="System.Windows.Forms.UnsafeNativeMethods+IHTMLLocation"><span style="color:windowtext;text-decoration:none;text-underline:none">IHTMLLocation</span></a> <span style="mso-bidi-font-weight:bold">location</span> = document.<a href="http://www.aisto.com/roeder/dotnet/Default.aspx?Object=11" title="UnsafeNativeMethods.IHTMLLocation System.Windows.Forms.UnsafeNativeMethods+IHTMLDocument2.GetLocation();"><span style="color:windowtext;text-decoration:none;text-underline:none">GetLocation</span></a>(); Gets the text URL: <a href="http://www.aisto.com/roeder/dotnet/Default.aspx?Object=12" title="System.String"><span style="color:windowtext;text-decoration:none; text-underline:none">string</span></a> <span style="mso-bidi-font-weight: bold">url</span> = location.<a href="http://www.aisto.com/roeder/dotnet/Default.aspx?Object=13" title="string System.Windows.Forms.UnsafeNativeMethods+IHTMLLocation.GetHref();"><span style="color:windowtext;text-decoration:none;text-underline:none">GetHref</span></a></li>
               /// <li style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; mso-list:l0 level1 lfo1;tab-stops:list .5in" class="MsoNormal">Creates a new URI from the URL and gets the host name.</li>
               /// <li style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; mso-list:l0 level1 lfo1;tab-stops:list .5in" class="MsoNormal">Test the Bloom Filter for the host name. If found then:</li>
               /// </ol>
               /// <p style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; margin-left:.8in;text-indent:-.3in;mso-list:l0 level2 lfo1;tab-stops:list .8in" class="MsoNormal"><span style="mso-list:Ignore">3.1.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;</span></span> Read from the configuration file the configured URL(document_completed_url property), set the host parameter using string.Format.</p>
               /// <p style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; margin-left:.8in;text-indent:-.3in;mso-list:l0 level2 lfo1;tab-stops:list .8in" class="MsoNormal"><span style="mso-list:Ignore">3.2.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;</span></span> Create a new web request for the created URL. Get the response stream, the result stream should be interpreted as number. If the number is not 0 then</p>
               /// <p style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; margin-left:1.1in;text-indent:-.35in;mso-list:l0 level3 lfo1;tab-stops:list 1.25in" class="MsoNormal"><span style="mso-list:Ignore">3.2.1.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> Read from the configuration file the configured URL(document_completed_0_responce_url property), set the host parameter and direct the web browser window navigator to the new location to open in a new window.</p>
               /// <p><!--EndFragment--></p>               /// </summary>
               /// <exception>ArgumentNullException if any parameter is null.</exception>
               /// <exception>HandleEventException to signal problems in handling the event.</exception>
               /// <param name='sender'>Sender object.</param>
               /// <param name='args'>Extension event arguments.</param>
               public void HandleEvent(object sender, Orpheus.Plugin.InternetExplorer.ExtensionEventArgs args) {
               
        // your code here
               
               }
             }

           }
         }
       }
     }
   }
 }
