insert into id_sequences (name, next_block_start, block_size, exhausted) values ('AddressIDGenerator', 1, 1, 0);
insert into id_sequences (name, next_block_start, block_size, exhausted) values ('ContactIDGenerator', 1, 1, 0);
insert into id_sequences (name, next_block_start, block_size, exhausted) values ('AuditIDGenerator', 1, 1, 0);
insert into company(company_id ,name , passcode , creation_date , creation_user , modification_date , modification_user) values ( -1 , 'dummy' , 'dummy', current ,'user' ,current,'user');
insert into company(company_id ,name , passcode , creation_date , creation_user , modification_date , modification_user) values ( 1 , 'dummy' , 'dummy', current ,'user' ,current,'user');
insert into company(company_id ,name , passcode , creation_date , creation_user , modification_date , modification_user) values ( 2 , 'dummy' , 'dummy', current ,'user' ,current,'user');
insert into company(company_id ,name , passcode , creation_date , creation_user , modification_date , modification_user) values ( 3 , 'dummy' , 'dummy', current ,'user' ,current,'user');
insert into account_status(account_status_id , description , creation_date , creation_user , modification_date , modification_user) values (-1 ,'dummy' ,current ,'user' ,current ,'user');
insert into user_account(user_account_id,company_id,account_status_id,user_name,password,creation_date,creation_user,modification_date,modification_user) values (-1 ,-1 ,-1 ,'dummy' ,'dummy' ,current ,'user' ,current,'user');
insert into user_account(user_account_id,company_id,account_status_id,user_name,password,creation_date,creation_user,modification_date,modification_user) values (1 ,-1 ,-1 ,'dummy' ,'dummy' ,current ,'user' ,current,'user');
insert into user_account(user_account_id,company_id,account_status_id,user_name,password,creation_date,creation_user,modification_date,modification_user) values (2 ,-1 ,-1 ,'dummy' ,'dummy' ,current ,'user' ,current,'user');
insert into user_account(user_account_id,company_id,account_status_id,user_name,password,creation_date,creation_user,modification_date,modification_user) values (3 ,-1 ,-1 ,'dummy' ,'dummy' ,current ,'user' ,current,'user');
insert into client(client_id ,name ,company_id ,creation_date ,creation_user ,modification_date ,modification_user) values ( -1,'dummy' ,-1 ,current ,'user' ,current,'user');
insert into client(client_id ,name ,company_id ,creation_date ,creation_user ,modification_date ,modification_user) values ( 1,'dummy' ,-1 ,current ,'user' ,current,'user');
insert into client(client_id ,name ,company_id ,creation_date ,creation_user ,modification_date ,modification_user) values ( 2,'dummy' ,-1 ,current ,'user' ,current,'user');
insert into client(client_id ,name ,company_id ,creation_date ,creation_user ,modification_date ,modification_user) values ( 3,'dummy' ,-1 ,current ,'user' ,current,'user');
insert into project(project_id ,company_id ,name ,description ,start_date ,end_date ,creation_date ,creation_user ,modification_date ,modification_user) values (-1 ,-1 ,'dummy' ,'dummy' ,current ,current ,current ,'user' ,current,'user');
insert into project(project_id ,company_id ,name ,description ,start_date ,end_date ,creation_date ,creation_user ,modification_date ,modification_user) values (1 ,-1 ,'dummy' ,'dummy' ,current ,current ,current ,'user' ,current,'user');
insert into project(project_id ,company_id ,name ,description ,start_date ,end_date ,creation_date ,creation_user ,modification_date ,modification_user) values (2 ,-1 ,'dummy' ,'dummy' ,current ,current ,current ,'user' ,current,'user');
insert into project(project_id ,company_id ,name ,description ,start_date ,end_date ,creation_date ,creation_user ,modification_date ,modification_user) values (3 ,-1 ,'dummy' ,'dummy' ,current ,current ,current ,'user' ,current,'user');
insert into application_area(app_area_id, description, creation_date, creation_user, modification_date, modification_user) values (1, 'Expense', current, 'user', current, 'user');
insert into application_area(app_area_id, description, creation_date, creation_user, modification_date, modification_user) values (2, 'Fixed Billing', current, 'user', current, 'user');
insert into application_area(app_area_id, description, creation_date, creation_user, modification_date, modification_user) values (3, 'Time', current, 'user', current, 'user');
insert into application_area(app_area_id, description, creation_date, creation_user, modification_date, modification_user) values (4, 'Client', current, 'user', current, 'user');
insert into application_area(app_area_id, description, creation_date, creation_user, modification_date, modification_user) values (5, 'Company', current, 'user', current, 'user');
insert into application_area(app_area_id, description, creation_date, creation_user, modification_date, modification_user) values (6, 'Project', current, 'user', current, 'user');
insert into application_area(app_area_id, description, creation_date, creation_user, modification_date, modification_user) values (7, 'User', current, 'user', current, 'user');
insert into application_area(app_area_id, description, creation_date, creation_user, modification_date, modification_user) values (8, 'Invoice', current, 'user', current, 'user');
insert into application_area(app_area_id, description, creation_date, creation_user, modification_date, modification_user) values (9, 'Notification', current, 'user', current, 'user');
insert into application_area(app_area_id, description, creation_date, creation_user, modification_date, modification_user) values (10, 'Configuration', current, 'user', current, 'user');
insert into address_type(address_type_id,description,creation_date,creation_user,modification_date,modification_user) values (1 , 'PROJECT', CURRENT, 'user', CURRENT, 'user');
insert into address_type(address_type_id,description,creation_date,creation_user,modification_date,modification_user) values (2 , 'CLIENT', CURRENT, 'user', CURRENT, 'user');
insert into address_type(address_type_id,description,creation_date,creation_user,modification_date,modification_user) values (3 , 'COMPANY', CURRENT, 'user', CURRENT, 'user');
insert into address_type(address_type_id,description,creation_date,creation_user,modification_date,modification_user) values (4 , 'USER', CURRENT, 'user', CURRENT, 'user');
insert into contact_type(contact_type_id,description,creation_date,creation_user,modification_date,modification_user) values (1 , 'PROJECT', CURRENT, 'user', CURRENT, 'user');
insert into contact_type(contact_type_id,description,creation_date,creation_user,modification_date,modification_user) values (2 , 'CLIENT', CURRENT, 'user', CURRENT, 'user');
insert into contact_type(contact_type_id,description,creation_date,creation_user,modification_date,modification_user) values (3 , 'COMPANY', CURRENT, 'user', CURRENT, 'user');
insert into contact_type(contact_type_id,description,creation_date,creation_user,modification_date,modification_user) values (4 , 'USER', CURRENT, 'user', CURRENT, 'user');
insert into country_name(country_name_id,name,creation_date,creation_user,modification_date,modification_user) values (1, 'China', CURRENT, 'user', CURRENT, 'user');
insert into country_name(country_name_id,name,creation_date,creation_user,modification_date,modification_user) values (2, 'USA', CURRENT, 'user', CURRENT, 'user');
insert into state_name(state_name_id,name,abbreviation,creation_date,creation_user,modification_date,modification_user) values (1, 'ZheJiang', 'ZJ', CURRENT, 'user', CURRENT, 'user');
insert into state_name(state_name_id,name,abbreviation,creation_date,creation_user,modification_date,modification_user) values (2, 'Alaska', 'AK', CURRENT, 'user', CURRENT, 'user');